name: Python application for markdown content validation

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - id: changed-files
      name: Get changed files
      uses: jitterbit/get-changed-files@v1
    
    - id: changed-files
      name: Get changed files
      uses: jitterbit/get-changed-files@v1

    - name: Verify submission details
      uses: bubriks/KTH-Course-content-verifier@master
      with:
        dsd: sdfs
        location: ^contributions/(.+)/(.+)/
		changes: ${{ steps.changed-files.outputs.all }}
        structure: >
          {
            "title": [
              "^# presentation:.*$",
              "^# essay:.*$",
              "^# demo:.*$",
              "^# open-source:.*$",
              "^# executable tutorial:.*$",
              "^# course automation:.*$",
              "^# feedback:.*$"
            ],
            "member": {
              "title": "^## members$",
              "memberOne": [
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                  "gitHub": "^github: https://github.com/[a-z]+$"
                },
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                }
              ],
              "memberTwo": [
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                  "gitHub": "^github: https://github.com/[a-z]+$"
                },
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                },
                {}
              ],
              "memberThree": [
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$",
                  "gitHub": "^github: https://github.com/[a-z]+$"
                },
                {
                  "nameAndEmail": "^[a-z]+( [a-z]+)* [a-z]+ \([a-z]+@kth.se\)$"
                },
                {}
              ]
            },
            "proposal": "^## proposal$"
          }
